version: 2.1

jobs:
  build:
    docker:
      - image: buildkite/puppeteer
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Build
          command: npm run bundle
      - run:
          name: Build
          command: npm run build:storybook
      - run:
          name: Check Linting
          command: npm run eslint
      - run:
          name: Run Tests
          command: npm test
